version: '3'
services:
    web:
        build: .
        container_name: web_pifuhd
        command: python3 main.py
        volumes:
            - ./app:/root
        restart: always
        ports:
            - 8001:8001